### ISSUE TITLE
[Question] penplot at a certain frame

### ISSUE THREAD

**Issue by jzting** [mattdesl/canvas-sketch-util#15]
Hi Matt, thank you for canvas-sketch and the penplot helper! I was wondering if it's possible to export an SVG at a particular frame. E.g. I am trying to run a Matter.js simulation and want to pause the sketch at a certain frame and export it to SVG.

**Comment by mattdesl** [comment]
Typically what I might do is something like: push the space bar to pause/play when you feel it's good, and then hit Cmd + S to export.

Or, if you want to programmatically do that, you can do something like this (not tested...)

```js
function sketch () {
  return (props) => {
    const { frame, playing, exporting } = props;

    // do your usual render and have a result,
    // e.g. the layers/SVG data
    const renderResult = doRender(props);

    // when we hit a certain frame, if we aren't playing/exporting...
    if (frame === 4 && playing && !exporting) {
      props.pause(); // stop simulation
      props.exportFrame(); // trigger export
    }

    // finally return that result
    return renderResult;
  };
}
```

**Comment by jzting** [comment]
Thank you! Will give this a try.

**Comment by jzting** [comment]
Thanks, this was super helpful! It turned out I had some issues with my rendering function.
